task_name: camouflage
eval_type: cod
model_checkpoint: /home/sunye_2/zhangchuhan/best_results/best_results/cod/model_epoch_best.pth

test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /share/test/sunye_2/zhangchuhan/COD/COD10K-v3/Test/Image
      root_path_2: /share/test/sunye_2/zhangchuhan/COD/COD10K-v3/Test/GT_Object
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 1024
  batch_size: 1

data_norm:
  inp:
    sub: [0.5]
    div: [0.5]
  gt:
    sub: [0.5]
    div: [0.5]
  gt_rgb:
    sub: [0.5]
    div: [0.5]

model:
  name: sam
  args:
    inp_size: 1024
    loss: iou
    encoder_mode:
      name: sam
      img_size: 1024
      mlp_ratio: 4
      patch_size: 16
      qkv_bias: true
      use_rel_pos: true
      window_size: 14
      out_chans: 256
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      prompt_embed_dim: 256
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor
      embed_dim: 1280
      depth: 32
      num_heads: 16
      global_attn_indexes: [7, 15, 23, 31]
